spring.application.name=Ai-Study-Hub

# Cấu hình kết nối Database
spring.datasource.url=jdbc:postgresql://localhost:5431/studyHubAI
spring.datasource.username=user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

javagroup.jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9V0+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfpP94DH6jBxBhFyBPaQQ==

javagroup.jwt.access-token-validity-in-seconds=86400
javagroup.jwt.refresh-token-validity-in-seconds=86400