spring.application.name=Ai-Study-Hub

# Cấu hình kết nối Database
spring.datasource.url=jdbc:postgresql://localhost:5431/studyHubAI
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

# Cấu hình Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cấu hình MinIO
minio.url=http://localhost:9000
minio.access.name=admin
minio.access.secret=12345678
minio.bucket.name=studyhub
